global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'comicbook-nginx-exporter'
    scrape_interval: 15s 
    metrics_path: /metrics
    static_configs:
      - targets: ['testcomic-service.comicbook.svc.cluster.local:9113'] 
