apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxcomicbook1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxcomic
  template:
    metadata:
      labels:
        app: nginxcomic
    spec:
      containers:
      - name: nginxcomic
        image: nginxcomic
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxcomicbook2
spec:
  selector:
    app: nginxcomic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxcomicbook3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/enable-underscores: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: devopsdaemonsdevops2022.de
    http:
      paths:
      - path: "/comicbook"
        pathType: Prefix
        backend:
          service:
            name: nginxcomicbook2
            port:
              number: 80
