apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allinone.yml
images:
  - name: testcomic
    newName: devops2022.azurecr.io/testcomic
    newTag: cab0edfbaee04608ff5c92888512001ff5893ea5
