apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allinone.yml
images:
  - name: nginxcomic
    newName: devops2022.azurecr.io/--newTag=e7eb243738bd25ae2041debbad6b88875e79ad24
    newTag: --newName=htmlcomic
