apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allinone.yml
images:
   - name: nginxcomic
     newName: devops2022.azurecr.io/comicbook
     newTag: c131af898e1ca585045e94630647b2467f9c90f1
