apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yml
  - service.yml
  - deployment.yml
images:
  - name: nginxcomic
    newName: comicbook:4d88f80a7bc83b18fc9d9d183167675db8f1bc96
