apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allinone.yml
  - kibana.yml
  #- mongodb.yml
images:
   - name: nginxcomic
     newName: devops2022.azurecr.io/comicbook
     newTag: 875ba9dcd25deb686eed53cae1df39ff9a483071
