apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.service.ingress.yml
images:
  - name: nginxcomic
    newName: comicbook:b0393970733c4460f85a0904cac3c626206b840a
