apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest
          env:
            - name: mongodb+srv://m001-student:YSId9v7lzJL79qsW@cluster0.ndhep.azure.mongodb.net/test
              valueFrom:
                secretKeyRef:
                  name: mongodb-connection
                  key: connection-string
