apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
    namespace: comicbook
data:
    nginx.conf: |
        worker_processes 1;
        events {
            worker_connections 1024;
        }
        http {
            server{
                location / {
                    root usr/share/nginx/html;
                    index index.html index.html;
                }
                location /nginx_status {
                 stub_status on;
                 access_log off;
                 }
            }

        }