apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: comicbook
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prom-config-map
              mountPath: /etc/prometheus 
      volumes:
        - name: prom-config-map
          configMap:
            name: prom-config-map 
