apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: comicbook
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
 